"use client"
import './globals.css'
import ContextWrapper from '@/components/Context/StateContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <ContextWrapper>
                <body>{children}</body>
            </ContextWrapper>
        </html>
    )
}
